#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

# parser.rb : generated by racc
  
module Cadenza
  class Parser < Racc::Parser

module_eval(<<'...end cadenza.y/module_eval...', 'cadenza.y', 63)
attr_reader :lexer

def initialize(options={})
  @lexer = options.fetch(:lexer, Cadenza::Lexer.new)

  raise "Lexers passed to the parser must define next_token" unless @lexer.respond_to?(:next_token)

  raise "Lexers passed to the parser must define source=" unless @lexer.respond_to?(:source=)
end

def parse(source)
  @lexer.source = source
  @document = DocumentNode.new
  do_parse
  @document
end

def next_token
  @lexer.next_token
end
...end cadenza.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    20,    17,    21,    22,    18,    32,    19,    33,    20,    17,
     9,    10,    11,    12,    13,     9,    10,    11,    12,    13,
     9,    10,    11,    12,    13,     9,    10,    11,    12,    13,
     9,    10,    11,    12,    13,     9,    10,    11,    12,    13,
     9,    10,    11,    12,    13,     9,    10,    11,    12,    13,
     1,    34,     4,    35,     1,    26,     4,    21,    22,    20,
    17,    20,    17,    21,    22,    26,    39,    15,    24 ]

racc_action_check = [
     7,     7,    25,    25,     7,    23,     7,    26,    23,    23,
    39,    39,    39,    39,    39,    33,    33,    33,    33,    33,
    22,    22,    22,    22,    22,     1,     1,     1,     1,     1,
    13,    13,    13,    13,    13,    21,    21,    21,    21,    21,
    17,    17,    17,    17,    17,    20,    20,    20,    20,    20,
     0,    28,     0,    28,     6,    34,     6,     8,     8,    36,
    36,    40,    40,    29,    29,    18,    37,     5,    15 ]

racc_action_pointer = [
    35,    23,   nil,   nil,   nil,    67,    39,   -10,    49,   nil,
   nil,   nil,   nil,    28,   nil,    68,   nil,    38,    63,   nil,
    43,    33,    18,    -2,   nil,    -6,    -6,   nil,    37,    55,
   nil,   nil,   nil,    13,    53,   nil,    49,    54,   nil,     8,
    51 ]

racc_action_default = [
    -2,   -26,   -23,   -24,   -22,   -26,    -1,   -26,   -11,    -3,
    -4,    -5,    -6,   -26,    -8,   -26,   -25,   -26,   -26,   -20,
   -26,   -26,   -26,   -26,    41,   -13,   -16,   -18,   -26,   -12,
    -9,   -10,    -7,   -26,   -26,   -21,   -14,   -17,   -19,   -26,
   -15 ]

racc_goto_table = [
     7,    27,     3,    25,    30,    31,    29,     6,    16,    37,
    28,     5,    23,   nil,   nil,   nil,   nil,    38,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    36,   nil,   nil,   nil,   nil,   nil,    40 ]

racc_goto_check = [
     4,     7,    10,     5,     3,     3,     5,     2,    10,     6,
     8,     1,     4,   nil,   nil,   nil,   nil,     7,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,    11,     7,   -17,    -1,   -14,   -24,   -17,    -8,   nil,
     2 ]

racc_goto_default = [
   nil,   nil,   nil,    14,   nil,     8,   nil,   nil,   nil,     2,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 19, :_reduce_none,
  0, 19, :_reduce_2,
  1, 21, :_reduce_3,
  1, 21, :_reduce_4,
  1, 21, :_reduce_5,
  1, 21, :_reduce_6,
  3, 21, :_reduce_7,
  1, 23, :_reduce_none,
  3, 23, :_reduce_9,
  3, 23, :_reduce_10,
  1, 22, :_reduce_none,
  3, 22, :_reduce_12,
  3, 22, :_reduce_13,
  1, 24, :_reduce_14,
  3, 24, :_reduce_15,
  1, 25, :_reduce_16,
  3, 25, :_reduce_17,
  1, 26, :_reduce_18,
  3, 26, :_reduce_19,
  3, 27, :_reduce_20,
  5, 27, :_reduce_21,
  1, 28, :_reduce_22,
  1, 28, :_reduce_none,
  1, 20, :_reduce_24,
  2, 20, :_reduce_25 ]

racc_reduce_n = 26

racc_shift_n = 41

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENTIFIER => 2,
  :INTEGER => 3,
  :REAL => 4,
  :STRING => 5,
  "(" => 6,
  ")" => 7,
  "*" => 8,
  "/" => 9,
  "+" => 10,
  "-" => 11,
  "," => 12,
  ":" => 13,
  "|" => 14,
  :VAR_OPEN => 15,
  :VAR_CLOSE => 16,
  :TEXT_BLOCK => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENTIFIER",
  "INTEGER",
  "REAL",
  "STRING",
  "\"(\"",
  "\")\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\",\"",
  "\":\"",
  "\"|\"",
  "VAR_OPEN",
  "VAR_CLOSE",
  "TEXT_BLOCK",
  "$start",
  "target",
  "document",
  "primary_expression",
  "additive_expression",
  "multiplicative_expression",
  "parameter_list",
  "filter",
  "filter_list",
  "inject_statement",
  "document_component" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'cadenza.y', 5)
  def _reduce_2(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 9)
  def _reduce_3(val, _values, result)
     result = VariableNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 10)
  def _reduce_4(val, _values, result)
     result = ConstantNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 11)
  def _reduce_5(val, _values, result)
     result = ConstantNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 12)
  def _reduce_6(val, _values, result)
     result = ConstantNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 13)
  def _reduce_7(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'cadenza.y', 18)
  def _reduce_9(val, _values, result)
     result = ArithmeticNode.new(val[0], "*", val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 19)
  def _reduce_10(val, _values, result)
     result = ArithmeticNode.new(val[0], "/", val[2]) 
    result
  end
.,.,

# reduce 11 omitted

module_eval(<<'.,.,', 'cadenza.y', 24)
  def _reduce_12(val, _values, result)
     result = ArithmeticNode.new(val[0], "+", val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 25)
  def _reduce_13(val, _values, result)
     result = ArithmeticNode.new(val[0], "-", val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 29)
  def _reduce_14(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 30)
  def _reduce_15(val, _values, result)
     result = val[0].push(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 34)
  def _reduce_16(val, _values, result)
     result = FilterNode.new(val[0].value) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 35)
  def _reduce_17(val, _values, result)
     result = FilterNode.new(val[0].value, val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 39)
  def _reduce_18(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 40)
  def _reduce_19(val, _values, result)
     result = val[0].push(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 44)
  def _reduce_20(val, _values, result)
     result = InjectNode.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 45)
  def _reduce_21(val, _values, result)
     result = InjectNode.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 49)
  def _reduce_22(val, _values, result)
     result = TextNode.new(val[0].value) 
    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'cadenza.y', 54)
  def _reduce_24(val, _values, result)
     @document.children.push(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'cadenza.y', 55)
  def _reduce_25(val, _values, result)
     @document.children.push(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Cadenza
